[versions]
agp = "8.13.0"
bouncycastle = "2.73.9"
jacksonDataformatToml = "2.20.1"
annotations = "26.0.2-1"

[libraries]
bcpkix-lts8on = { module = "org.bouncycastle:bcpkix-lts8on", version.ref = "bouncycastle" }
bcprov-lts8on = { module = "org.bouncycastle:bcprov-lts8on", version.ref = "bouncycastle" }
jackson-dataformat-toml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-toml", version.ref = "jacksonDataformatToml" }
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

